Number pools
Nexmo/api-specification pull request #355
Opened 2020-08-27 13:30 UTC by dragonmantank

# Description

## New 

* Working on number pools spec

Mostly need this PR right now to have a sample render.

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

2020-09-16 16:36 UTC, lornajane commented
I made a couple of changes to have spectral run locally, and I also have some comments in general on this spec (I'm not sure how much of this you inherited).

The responses all seem to point deep into a response schema, so I fixed one error by adjusting where it was referred to to match. I'm not sure about the value of having the shared "Error" object with a lot of AllOf attached since many tools won't handle the AllOf correctly and you're basically redefining the error type each time.

I also had to remove some required field indicator from `CreatePool` (it was making Spectral spit errors), again it's an AllOf structure with some overrides and I'm not sure how many tools will appreciate the optimisation. I think the same thing would cause a problem in UpdatePool but that object isn't currently referenced anywhere in the spec. Top tip: remove the line in `.spectral.yml` that says the Voice API needs it and re-run the lint locally to identify unused sections. Although I assume this is more like under construction than orphaned code!

2020-09-16 16:46 UTC, dragonmantank commented
> The responses all seem to point deep into a response schema, so I fixed one error by adjusting where it was referred to to match. I'm not sure about the value of having the shared "Error" object with a lot of AllOf attached since many tools won't handle the AllOf correctly and you're basically redefining the error type each time.

That was the easiest way to sketch up errors that are all the same format. You can use `allOf` and reference a schema + an object, and the object descriptions will get pulled through. Much easier than redefining a 7807 error multiple times. That was the only recommended way to handle updating descriptions for the moment, until the next version of OpenAPI lands and you can update reference descriptions.

2020-10-15 21:03 UTC, slorello89 requested changes
Some questions about some response types, some minor inconsistencies. Questions about the `pool_id` and `account_id` parameter and the validity of having account/pool nested.

2020-10-15 21:03 UTC, slorello89 commented on definitions/number-pools.yml
> +        If all items succeed, you will receive a `200`. If all items fail, you will receive a `400`.
It says you'll receive a 200 if everything is successful, response is a 204

2020-10-16 09:47 UTC, lornajane commented on definitions/number-pools.yml
> +            $ref: '#/components/schemas/ErrorInvalidParameters'
422 is a WebDAV response code rather than an HTTP one so I'm not sure about using that

2020-10-16 16:20 UTC, dragonmantank commented on definitions/number-pools.yml
> +            $ref: '#/components/schemas/ErrorInvalidParameters'
The example can be changed

2020-10-16 16:21 UTC, dragonmantank commented on definitions/number-pools.yml
> +        account_id:
API Keys are account IDs. In this case, we're not using it for authentication but as routing for which account to use for the pool

2020-10-16 16:22 UTC, dragonmantank commented on definitions/number-pools.yml
> +    PoolId:
Number Pools are sub-account aware, so for consistency we provide the account ID at all times. Otherwise we'd have paths for the primary account and paths for sub accounts.

The decision was made that users can generate the pools IDs themselves, so it's user configurable. This keeps it inline with the current pool system.

2020-10-16 16:24 UTC, dragonmantank commented on definitions/number-pools.yml
> +    ErrorAddNumbersResponse:
422 is a Webdav-specific HTTP error, so keeping with HTTP ones where possible it drops back down to a 400.

2020-10-16 16:25 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorTooManyNumbersResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible

2020-10-16 16:25 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorAddNumbersResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible

2020-10-16 16:25 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorInvalidUpdatePoolResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible

2020-10-16 16:25 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorCouldNotDeleteFromPoolResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible

2020-10-16 16:25 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorTooManyNumbersResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible (I think my record is broken :P)

2020-10-16 16:28 UTC, dragonmantank commented on definitions/number-pools.yml
> +    post:
We went back and forth on this. Technically `DELETE` deletes a resource and isn't meant for bulk operations. There's also the problem of query-string length limitations that many servers and clients have, but we need to be able to handle large bulk deletions. Taking the max length of MSISDNs (which is actually slated to get bigger), that left us with a very tiny amount we can pass in the query string.

In this case we decided to go somewhat RPC for this one endpoint and allow the user to `POST` against a discreet delete endpoint that will handle bulk operations.

There is a `DELETE` route for deleting individual numbers however.

2020-10-16 16:29 UTC, dragonmantank commented on definitions/number-pools.yml
> +        If all items succeed, you will receive a `200`. If all items fail, you will receive a `400`.
Should be `201` and `207`, will update the description. The response codes changed after-the-fact.

2020-10-16 16:30 UTC, dragonmantank commented on definitions/number-pools.yml
> +  /v2/pools/{account_id}/{pool_id}:
Yes, because the system is sub-account aware. Pools are managed on a per-account level.

2020-10-16 16:30 UTC, dragonmantank commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorInvalidParametersResponse/content/application~1json/schema'
Going for HTTP instead of WebDav when possible

2020-10-16 16:39 UTC, slorello89 commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorTooManyNumbersResponse/content/application~1json/schema'
Fine :P Still `ErrorTooManyNumbersResponse` should be a 413 in that case - 400 is very specifically invalid syntax - I buy that if there's a type mismatch (it's a stretch but I'll buy it) - but the content length is literally too long lol.

2020-10-16 16:44 UTC, slorello89 commented on definitions/number-pools.yml
> +    ErrorAddNumbersResponse:
again fine with not using Webdav, In this case it should either be a 403 or 404. 400 isn't correct here semantically

2020-10-16 16:46 UTC, slorello89 commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorCouldNotDeleteFromPoolResponse/content/application~1json/schema'
Fine with not using 422, in this case it's referring to numbers that you aren't subscribed to so I would think it should be phrased as either a 403 as you're forbidden from adding it to the pool, or a 404 as it's not found

2020-10-16 16:46 UTC, slorello89 commented on definitions/number-pools.yml
> +    post:
I buy it as an RPC operation

2020-10-16 16:47 UTC, slorello89 commented on definitions/number-pools.yml
> +                  - $ref: '#/components/responses/ErrorTooManyNumbersResponse/content/application~1json/schema'
In this case, the payload size is too large so it should be 413

2021-12-15 16:35 UTC, pardel approved these changes

2021-12-15 16:35 UTC, merged