Add WebSocket Call product
Nexmo/api-specification pull request #356
Opened 2020-08-28 12:36 UTC by vshisterov

# Description

New report type and corresponding `product` value supported: `WEBSOCKET-CALL`.

# Checklist

- [x] version number incremented (in the `info` section of the spec)

2020-09-14 07:09 UTC, bencgreenberg commented
@tbedford, As the Reports API specialist, want to take a peek at this?

2020-10-07 08:47 UTC, lornajane commented on definitions/reports.yml
> +    WEBSOCKET-CALL:
Why are these schema names uppercase? We don't have naming checks on these fields (or it only emits a warning, not sure), do you know if this is like this for a reason (I realise this one just follows the others)

2020-10-07 08:48 UTC, lornajane commented
@vshisterov I see this has been open for a while, what's the status of this feature?

2020-10-09 09:07 UTC, vshisterov commented on definitions/reports.yml
> +    WEBSOCKET-CALL:
I have no idea, to be honest - as you said, I was following what is already in the spec. "Bad Consistent > Good Inconsistent" :)

2020-10-09 09:08 UTC, vshisterov commented
> @vshisterov I see this has been open for a while, what's the status of this feature?

It's in production for more than a month already (the Reports API support for WS). The docs still just awaiting approval for the merge per my understanding.

2020-10-12 11:02 UTC, tbedford requested changes
For 'get records' I don't see the product in the example response, however it's there for 'Create an asynchronous report'.

2020-10-12 11:04 UTC, tbedford commented on definitions/reports.yml
> +    WEBSOCKET-CALL:
It's probably because the product names are uppercase in the responses. I also just followed existing usage.

2020-10-12 11:05 UTC, tbedford commented
Sorry, for some reason this one fell through the cracks. I deal with a LOT of PRs and usually respond to them very quickly. Apologies this one got missed.

2020-10-13 16:09 UTC, tbedford approved these changes

2020-10-13 16:29 UTC, merged