10DLC Public API
Nexmo/api-specification pull request #372
Opened 2020-10-20 13:28 UTC by dragonmantank

# Description

Public API design work against the new 10DLC rules. The branch mostly exists at this point to make it easy to collaborate, and is in no way ready for review or public consumption.

2020-10-22 20:17 UTC, slorello89 requested changes
Lot's of things need descriptions

Campaigns is a nested resource under brands which is something I think we should not have

Auth is missing.

A bunch of stuff doesn't expand properly in the renderer

A couple of endpoints that I think should either be removed or repurposed.

some missing parameters for pagination

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns:
Can we axe the brand_id from the path and put it as a query parameter? Shouldn't I be able to list all of the campaigns my account actively has going?

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns:
will have downstream effects on all the HATEOS stuff

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +      summary: Remove a specific number from a campaign
does this have any value? we have the bulk delete - can't we just use that instead and just pass in a one element array? sounds like something the SDKs should be working off of.

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +    description: APIs relating to working with Campaigns`
there's a hanging ` at the end of this.

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +      - $ref: '#/components/parameters/BrandId'
Missing pagination parameters

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +    UseCase:
I think we need a solid enumeration for this.

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +        Check to see if a brand is qualified to run a campaign against a given
I don't think we should have this endpoint. If you try to create a campaign with an invalid use case then it should be rejected by the create campaign endpoint as a 403. I could see the value in having a List use cases endpoint that lists all of the use cases and tells you whether your brand is permitted to use them or not. But having a pre-flight validation step doesn't make a lot of sense to me.

2020-10-22 20:17 UTC, slorello89 commented on definitions/10dlc.yml
> +openapi: 3.0.3
Assuming we're using basic - but I wonder - should we consider some type of JWT auth in this case? I could see the ACLs being very valuable to someone creating an internal dashboard. E.g. permit someone to create campaigns but not delete brands.

2020-10-28 17:43 UTC, dragonmantank commented on definitions/10dlc.yml
> +openapi: 3.0.3
We aren't 100% sure which auth is being used as we're working out the backend architecture details. This API draft it's near completion yet :P

2020-10-28 17:44 UTC, dragonmantank commented on definitions/10dlc.yml
> +    # get:
There will be eventually, was working through the happy path on a new campaign registration

2020-10-28 17:46 UTC, dragonmantank commented on definitions/10dlc.yml
> +        Check to see if a brand is qualified to run a campaign against a given
This is the formal workflow from the campaign management registry. We have to check this before any new campaign  back through as part of the qualification process. We _might_ be able to wrap this but right now for the MVP API we're looking at just stepping through.

2020-10-28 17:47 UTC, dragonmantank commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns:
Campaigns only exist under a brand, so they are a sub-resource.

2020-10-28 17:48 UTC, dragonmantank commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns/{campaign_id}:
Like above, campaigns are part of a brand, so it's a sub-resource.

2020-10-28 17:49 UTC, dragonmantank commented on definitions/10dlc.yml
> +      summary: Stop a specific campaign on a brand
Looking into this. I'm not sure the resource is ever formally deleted, but the campaign is effectively stopped. There's still a bunch of unknowns around this.

2020-10-28 17:50 UTC, dragonmantank commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns/{campaign_id}/numbers:
See above reasons :P

2020-10-28 17:51 UTC, dragonmantank commented on definitions/10dlc.yml
> +      summary: Remove a specific number from a campaign
This endpoint may get the axe at some point, yes. There are still some questions against the number registry that need figured out that might completely invalidate this.

Numbers are technically a resource though, so we should provide the proper management of a single resource.

2020-10-28 17:52 UTC, dragonmantank commented on definitions/10dlc.yml
> +              quarterly_fee:
USD, as this is a US-only API.

2020-10-28 17:55 UTC, dragonmantank commented on definitions/10dlc.yml
> +                  $ref: '#/components/schemas/UseCaseMNOMetadata'
It's not expanding properly because our renderer doesn't seem to understand `additionalProperties` to make this render properly. It is a single object, with each property being the MNO (Mobile Number Operator) ID and value being the response.

2020-10-28 17:57 UTC, dragonmantank commented on definitions/10dlc.yml
> +        display_name:
The original spec we're working off of does not specify them, so fun times!

2020-10-28 17:59 UTC, dragonmantank commented on definitions/10dlc.yml
> +    UpdateIndividualBrand:
We're not sure exactly of the constraints right now, they just list mandatory fields. The campaign registry API makes it work as if an individual could register a stock symbol. We'll need to restrict that on our side at some point, but right now it's valid.

2020-10-28 18:47 UTC, slorello89 commented on definitions/10dlc.yml
> +                  $ref: '#/components/schemas/UseCaseMNOMetadata'
any reason we can't just remove the `additionalProperties` and the `type` and have this live at the top level?

2020-10-28 18:48 UTC, slorello89 commented on definitions/10dlc.yml
> +        display_name:
going to keep this open - something we may want to keep an eye on lol

2020-10-28 18:52 UTC, slorello89 commented on definitions/10dlc.yml
> +              quarterly_fee:
good then specifying won't be a problem :P

2020-10-28 18:55 UTC, slorello89 commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns:
I got that campaigns are only identifiable under brands and I'm not disputing the validity of that. but if the campaigns are uniquely addressable why would we want to force people to also know their brand ID as well?

2020-10-28 18:56 UTC, slorello89 commented on definitions/10dlc.yml
> +  /v1/10DLC/brands/{brand_id}/campaigns:
Make the brand_id a required field in the creation request, and you can query campaigns by their brand_id by just passing the brand_id as a query parameter.

2020-11-26 13:01 UTC, mheap requested changes
Added some questions, plus we need descriptions for all fields

2020-11-30 14:01 UTC, dragonmantank commented on definitions/10dlc.yml
> +        - state
Good question. The spec from the campaign registry requires it, and as of right now I don't believe we have gotten a good answer back on how to handle this. I think they push toward using a dedicated short code or a toll free number.

2020-11-30 14:02 UTC, dragonmantank commented on definitions/10dlc.yml
> +            - PRIVATE_PROFIT
Yup, these come from the campaign registry we are integrating with.

2020-11-30 14:06 UTC, dragonmantank commented on definitions/10dlc.yml
> +  /v1/10DLC/brands:
It is as a placeholder for the moment. I believe the MVP that's being used for the dashboard at the moment doesn't need base URL at all.

2021-06-04 16:07 UTC, dragonmantank commented on definitions/10dlc.yml
> +        campaign_count:
This was corrected at some point

2021-06-04 16:10 UTC, dragonmantank commented on definitions/10dlc.yml
> +        - state
For documentation - an EU company can give their actual EU address and tax info, TCR now accepts non-US information but still uses US terms

2021-11-12 15:25 UTC, pardel approved these changes

2021-11-12 17:01 UTC, merged