Added new fields to send SMS to comply with DLT (India) regulations
Nexmo/api-specification pull request #402
Opened 2020-11-25 10:13 UTC by GregHolmes

# Description

**Note**, this should not be merged until Monday due to this being when the feature is going to be deployed.

To make sure that our APIs meet new regulations, we're adding two new fields to the send-sms endpoint. These are `entity-id` and `content-id`. The first of these regulations is DLT, which is an Indian regulation, but we're expecting more regulations from other countries in the future, so these two fields are being kept as generic as possible. For more information on DLT please go to: https://help.nexmo.com/hc/en-us/articles/204017423-India-Features-Restrictions (I am currently drafting up a small addition to this page instructing users sending SMS to India, to use these two fields. So linking the two docs together).

# New 

* Added two new fields to `https://rest.nexmo.com/sms/:format` called `entity-id` and `content-id` which are both strings with no defined length. Discussed this with the API team implementing this feature, and there's also no validation. The fields are simply forwarded on if they're provided.

# Checklist

- [x] version number incremented (in the `info` section of the spec)

2020-11-25 13:27 UTC, marklewin requested changes
I'm just suggesting a more concise way of describing this?

2020-11-25 13:27 UTC, marklewin commented on definitions/sms.yml
>            description: "**Advanced**: A string only required when needing to meet certain country regulations by providing this field when making an SMS request. For more information please refer to
```suggestion
          description: "**Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://help.nexmo.com/hc/en-us/articles/115011781468)"
```

2020-11-25 13:27 UTC, marklewin commented on definitions/sms.yml
>            description: "**Advanced**: A string only required when needing to meet certain country regulations by providing this field when making an SMS request. For more information please refer to
```suggestion
          description: "**Advanced**: A string parameter that satisfies regulatory requirements when sending an SMS to specific countries. For more information please refer to the [Country-Specific Outbound SMS Features](https://help.nexmo.com/hc/en-us/articles/115011781468)"
```

2020-11-27 09:13 UTC, GregHolmes commented
Just to add an update. The release has been pushed back by a week. And there will be some error codes added to the API. Just waiting on them to be finalised, then I'll add them to the branch.

2020-12-17 09:44 UTC, marklewin approved these changes
LGTM @GregHolmes !

2020-12-17 10:50 UTC, merged