Add Languages
Nexmo/api-specification pull request #430
Opened 2021-05-05 16:59 UTC by sammachin

added new language codes and styles to talk action.

Moved json schema to subfolder

2021-05-05 18:32 UTC, dragonmantank requested changes
#TabsVsSpaces

2021-05-05 18:32 UTC, dragonmantank commented on json-schemas/ncco-schema.json
> +			"language" : {
Can you switch to spaces to help clean up the whitespace?

2021-05-06 15:31 UTC, sammachin commented on json-schemas/ncco-schema.json
> +			"language" : {
oops! should be corrected now

2021-05-19 13:46 UTC, dragonmantank approved these changes

2021-05-19 13:46 UTC, merged