Meetings API - Phase 1
Nexmo/api-specification pull request #431
Opened 2021-05-06 08:47 UTC by abadyan-vonage

This is an initial draft of the first phase of the Meetings API.
The endpoints provided here are mostly used to address the VCC product use case.
We plan to add more capabilities to the API as more product use cases are defined.

2021-05-06 13:28 UTC, dragonmantank commented
Our general guidelines: https://nexmo.github.io/api-standards/

A few general comments to help keep similarity with our other APIs:

**HAL+JSON**
We generally use HAL+JSON as the structure for most of our responses. This makes it easier for us to roll out code in tooling, and for our API specs to more easily be digested by other client tools. This means using `_embedded` for "search" results like root `GET` requests. So for something like `GET /api/rooms` it would move to something like:

```json
{
   "_embedded": {
      "rooms": [ ... ]
   }
}
```

For the resources themselves, `_links` would be preferable for the meeting links. For example, when getting a room:

```json
{
  "id": "abc123",
  "display_name": "abc123",
  "pin_code": "123456789",
  "_links": {
      "guest_url": {
         "href": "https://meetings.vonage.com/123456789"
      },
      "host_url": {
         "href": "https://meetings.vonage.com/123456789?participant_token=xyz"
      }
   }
}
```

**Search Results**
When possible, for "search" type listings like `GET /api/rooms`, we should provide paging results so that users can more easily consume large data sets. We like to return the following data when appropriate:

* page_size
* page
* total_pages
* total_items

We also return a series of `_links` for moving from one page of the result set to the next. So expanding on the rooms listing:

```json
{
  "page_size": 100,
  "page": 3,
  "total_pages": 8,
  "total_items": 814,
   "_embedded": {
      "rooms": [ ... ]
   },
   "_links": {
    "self": {
      "href": "https://example.com/resource?page_size=100&order=asc&page=3"
    },
    "next": {
      "href": "https://example.com/resource?page_size=100&order=asc&page=4"
    },
    "prev": {
      "href": "https://example.com/resource?page_size=100&order=asc&page=2"
    },
    "last": {
      "href": "https://example.com/resource?page_size=100&order=asc&page=8"
    }
  }
}
```

2021-05-06 14:30 UTC, syzhakov approved these changes
lgtm

2021-05-06 14:30 UTC, syzhakov commented on definitions/meetings.yml
> +          type: string
no max length?

2021-05-06 14:30 UTC, syzhakov commented on definitions/meetings.yml
> +          - paused
is there really a paused status?

2021-05-06 14:30 UTC, syzhakov commented on definitions/meetings.yml
> +          example: en-US
sometimes you use quotation marks for string examples and sometimes not. stick to one convention (imho there should be quotations)

2021-05-06 14:30 UTC, syzhakov commented on definitions/meetings.yml
> +          example: United states
capital "s" in "states"

2021-05-10 13:36 UTC, ggoldens commented on definitions/meetings.yml
> +          - paused
If all the clients disconnect the session or no one is publishing, then the archiving goes to a "paused" state. When someone starts publishing, the status changes back to "started".

2021-05-10 14:06 UTC, ggoldens reviewed
Thanks! I've left a few comments/questions.

2021-05-10 14:06 UTC, ggoldens commented on definitions/meetings.yml
> +        id:
Is this the archive id generated by OpenTok or is it an internal id?
Why we use the terminology "Recordings" instead of "Archives"? Is it because in VBC you use "recordings"?

2021-05-10 14:06 UTC, ggoldens commented on definitions/meetings.yml
> +openapi: 3.0.0
No need to change anything, but FYI I think there's already the version 3.1.0.

2021-05-11 07:04 UTC, abadyan-vonage commented on definitions/meetings.yml
> +          enum:
I don't think we currently store failed recordings information. What would be the value for the user?

2021-05-11 07:04 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        "201":
good idea, will add it.

2021-05-11 07:08 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        session_id:
why do you think that is important here?

2021-05-11 07:27 UTC, abadyan-vonage commented
@dragonmantank Thanks for your comments, I will work them into the API.
@ggoldens - I meant VCC. This is the first use case of this API. For more information: https://docs.google.com/document/d/1Xy0SmvuS41ES9XVoa0serGQIOoROx1WCxwfAE5YB79s/edit?ts=6093d6be#heading=h.7imcm9l63yer

2021-05-11 13:33 UTC, ggoldens commented on definitions/meetings.yml
> +        id:
Sorry, no need to change it. If you use already the terminology recording that's fine. Just wanted to understand :)

2021-05-11 13:37 UTC, ggoldens commented on definitions/meetings.yml
> +        session_id:
I thought there should we a way to know to which room Id this recording belongs, but if the relationship is with a session Id then that's fine. 
It is not very clear to me how you relate a room, a session, and a recording.

2021-05-12 19:46 UTC, v-kpheng commented
Thanks for this @abadyan-vonage.  🙏 

Just curious, when will this documented be upgraded from `Draft`?  Is it still pending more use cases before it can be reviewed further and then accepted and finalized?  Please advise.  Thanks!

2021-05-12 20:18 UTC, v-kpheng reviewed
Looks good! 💪 

That said, left some comments.  Thanks!

2021-05-13 11:51 UTC, abadyan-vonage commented on definitions/meetings.yml
> +      operationId: getRooms
will add support per @dragonmantank 's comments.

2021-05-13 11:52 UTC, abadyan-vonage commented on definitions/meetings.yml
> +          description: OK
it might fail in a general way but there is no known use case for this.

2021-05-13 11:53 UTC, abadyan-vonage commented on definitions/meetings.yml
> +          format: date-time
it's iso-8601 time.

2021-05-13 11:56 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        "201":
Don't see a reason to add other codes here. Do you think I'm missing something?

2021-05-13 11:58 UTC, abadyan-vonage commented on definitions/meetings.yml
> +          description: Room not found
401 and 500 are general error codes that can always occur on any endpoint (except those that don't need auth). I don't see much value in repeating them over and over again.
400 doesn't seem to be applicable here as it's just a GET request.

2021-05-13 11:59 UTC, abadyan-vonage commented on definitions/meetings.yml
> +  /sessions/:session_id/recordings:
I addressed the 500 error code issue in other threads.

2021-05-13 12:00 UTC, abadyan-vonage reviewed
> Thanks for this @abadyan-vonage. 🙏
> 
> Just curious, when will this documented be upgraded from `Draft`? Is it still pending more use cases before it can be reviewed further and then accepted and finalized? Please advise. Thanks!

I plan to add documentation for the events we will be sending and address the initial comments raised here. That is when this would go into a final PR state.

2021-05-13 12:48 UTC, v-kpheng commented on definitions/meetings.yml
> +        "201":
What about `401`, in case user hasn't been authenticated?  Or `403`, if user is authenticated but lacks sufficient access?

2021-05-13 12:50 UTC, v-kpheng commented on definitions/meetings.yml
> +          description: Room not found
200 is a general status code too :-) 

(And you've included it in this API...)

2021-05-13 13:04 UTC, abadyan-vonage commented on definitions/meetings.yml
> +          description: Room not found
Some APIs return 200, some 201, some 202, so it's not that general.

2021-05-13 13:07 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        "201":
401 is a general error that might always be returned. 403 is specified where it makes sense (like when deleting recordings).

2021-05-18 02:51 UTC, jeffswartz requested changes

2021-05-18 02:51 UTC, jeffswartz commented on definitions/meetings.yml
> +        session_id:
I am also unclear on the relationship between rooms and sessions. Do these sessions correspond to OpenTok sessions? Do rooms have multiple sessions?

2021-05-18 02:51 UTC, jeffswartz commented on definitions/meetings.yml
> +        id:
Does the recording correspond to an OpenTok archive?

2021-05-18 02:51 UTC, jeffswartz commented on definitions/meetings.yml
> +        display_name:
I think properties should be camelCase (not snake_case): `displayName`, `pinCode`, `guessUrl`, `hostUrl`, etc.

2021-05-18 02:51 UTC, jeffswartz commented on definitions/meetings.yml
> +        session_id:
I think all properties should use camelCase (not snake_case).

2021-05-18 08:45 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        id:
yes

2021-05-18 08:47 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        session_id:
Rooms are permanent addresses (basically a pin code) that can be connected to multiple times. Each time somebody joins a room that was empty until then, a new session starts. After the last participant leaves, the session is closed.
I think this is not exactly the OpenTok session concept.

2021-05-18 08:48 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        display_name:
The standard says camel_case:
https://nexmo.github.io/api-standards/standard/property-names/

2021-05-19 09:34 UTC, abadyan-vonage commented on definitions/meetings.yml
> +openapi: 3.0.0
From what I saw, most editors don't yet support 3.1. Should we use the new version?

2021-05-19 13:40 UTC, dragonmantank commented on definitions/meetings.yml
> +          description: Room not found
As a general rule we don't document 500 errors in the spec because there could be any number of reasons we fail. 

Individual 2xx and 4xx errors are fair game though and should be as accurately represented as possible.

2021-05-20 05:19 UTC, jeffswartz commented on definitions/meetings.yml
> +        session_id:
I am concerned that we will run into problems if "session" does not correspond to an OpenTok (Video API) session. Developers that use the Meetings API may use Video API ecosystem tools or read our documentation, and the conflicting terminology could be confusing.

Can we think of a different term? What constitutes a `session` in the Meetings API?

2021-05-20 07:10 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        session_id:
A `session` in this context is a specific occurrence of participants entering a room and then leaving. The session starts when the first participant joins the room and ends when the last one leaves. It can have recordings (archives) associated to it.
Jeff, you are touching one of our main points of deliberation. We went back and forth with this issue, considering `session` vs `meeting` for this entity. The main concern about `session` is the confusion with OpenTok `session` and the main concern for `meeting` is that it might be confused with the concept of a recurring meeting (for which we would have a session per occurrence).
Would like to get some more opinions on this - what do you think is the right terminology here?

2021-05-20 13:53 UTC, abadyan-vonage commented
Made some changes trying to accommodate the comments here. Please review again and let me know what you think.

2021-05-28 18:39 UTC, jeffswartz commented on definitions/meetings.yml
> +        session_id:
RIght, @abadyan-vonage, the OpenTok meeting is close but it does not appear to match the concept of a session in the Meetings API. Also, for recurring meetings, do you reuse the same OpenTok session? Similar apps, like the [freeconferencing app](https://freeconferencing.vonage.com/), reuse the same OpenTok session for recurring uses of a room. Having a recurring meeting reuse the same OpenTok session, but then calling individual gatherings "sessions" (in the Meetings API) could lead to much confusion (as I've said). I don't have any proposed solution.

2021-05-30 07:07 UTC, abadyan-vonage commented on definitions/meetings.yml
> +        session_id:
We don't reuse tokbox session. I think it would be better to have a single word term for this and not reuse `room` in the second level object as that would create more confusion and make the api addresses hard to use.

2021-06-01 16:54 UTC, jeffswartz requested changes

2021-06-01 16:54 UTC, jeffswartz commented on definitions/meetings.yml
> +        pin_code:
I think we proposed changing `pin_code` (and `pincode`) to `meeting_code`. If so, please make that change here and throughout the API proposal.

2021-06-01 16:54 UTC, jeffswartz commented on definitions/meetings.yml
> +        session_id:
My understanding is that the `session_id` actually is an OpenTok (Vonage Video API) session ID. If so, we can leave this as is, an you can ignore other comments.

2021-06-04 14:21 UTC, jeffswartz approved these changes

2021-06-22 09:15 UTC, TomF-NVM commented on definitions/meetings.yml
> +              description: A notification about a becoming inactive, which means no more sessions can be created for it
Missing the word "room"

2021-12-05 11:52 UTC, abadyan-vonage commented
@pardel is there anything stopping us from merging this PR in at this moment?

2021-12-10 14:23 UTC, pardel commented
@abadyan-vonage There are some issues with it still unfortunately. See deployment at: https://nexmo-api-spec-pr-431.herokuapp.com/meetings

URLs for the operations are missing hostnames. eg: `:///api/rooms`
Also, all webhooks should be grouped under a Webhooks section - eg: https://nexmo-api-spec-pr-431.herokuapp.com/messages-olympus#webhooks

2021-12-12 08:14 UTC, abadyan-vonage commented
@pardel I updated the general info to be more accurate.
Regarding webhooks, I don't understand the example in the link that you gave. They seem to be using both some tag named x-webhooks and also the callbacks section under the operation itself, both with different schemas. 
Is there some guideline on how exactly to define the webhooks in the swagger?

2021-12-13 11:47 UTC, pardel commented
@abadyan-vonage there seems to be a mistake in that example I gave you - they are separate webhooks and should appear together under the Webhooks section. 
Please use this for guidance: https://github.com/Nexmo/api-specification/blob/bc8780291e95e0216a9b030d13ed4cbd7e9a4955/definitions/messages-olympus.yml#L378
Anything under the x-webhooks is rendered under that webhooks category.
NB: is a very recent addition to OpenAPI (v3.1) - you can find some examples here: https://github.com/OAI/OpenAPI-Specification/tree/main/examples/v3.1

2021-12-13 12:10 UTC, abadyan-vonage commented
@pardel done

2021-12-15 17:29 UTC, pardel approved these changes

2021-12-15 17:29 UTC, merged