add psip
Nexmo/api-specification pull request #482
Opened 2022-04-05 10:43 UTC by abdulajet

# Description

<!--

The following will be used in our release notes and public changelog. Communicate well!

Example:

# New 

Adding PSIP Definitions

# Checklist

- [x] version number incremented (in the `info` section of the spec)

2022-04-05 12:41 UTC, pardel approved these changes

2022-04-05 12:42 UTC, pardel requested changes
investigating why staging app not working

2022-05-06 11:06 UTC, SMadani approved these changes

2022-05-06 11:37 UTC, SMadani commented
Merged in #489

2022-05-06 11:37 UTC, closed without merging