Added callout for network unblock
Nexmo/api-specification pull request #511
Opened 2022-07-28 11:40 UTC by SecondeJK

# Description

By request of product, we need a callout to let developers know that the network unblock feature is only available
on request.

# New 

* Added callout to Network Unblock section of Verify v1 under Fraud Management.

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

2022-07-28 12:14 UTC, SMadani commented on definitions/verify.yml
> +        <i></i>
Why is this empty?

2022-07-28 12:34 UTC, pardel commented on definitions/verify.yml
> +        <i></i>
Can we also avoid using HTML tags in here?

2022-07-28 15:20 UTC, superchilled requested changes
Check failing for version bump.

Also see my comment re line 528

2022-08-01 10:38 UTC, superchilled approved these changes

2022-08-01 13:34 UTC, merged