APIDB-9753 add missing capabilities
Nexmo/api-specification pull request #562
Opened 2022-11-15 11:46 UTC by francesco-fipertani-vonage

# Description

# Checklist

- [ ] version number incremented (in the `info` section of the spec)

2022-11-15 12:05 UTC, pardel requested changes
This is a regression on the previous specs - can we make sure we're iterate on the current version (https://developer.vonage.com/api/application.v2). Lots of details are missing.

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +            room_changed:
Needs a description.

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +            session_changed:
Needs a description.

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +            recording_changed:
Needs a description.

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +                http_method:
shouldn't this be an enum?

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +                http_method:
shouldn't this be an enum?

2022-11-15 12:05 UTC, pardel commented on definitions/application.v2.yml
> +                http_method:
shouldn't this be an enum?

2022-11-17 13:29 UTC, francesco-fipertani-vonage commented on definitions/application.v2.yml
> +      description: Verify related configuration
Not sure what you mean with this. This is the v2 documentation...

2022-11-17 14:56 UTC, pardel requested changes

2022-11-17 14:56 UTC, pardel commented on definitions/application.v2.yml
> +        payment_enabled:
Is this property public? It's an addition on this spec.
If public, we need a better description.

2022-11-17 14:56 UTC, pardel commented on definitions/application.v2.yml
> +        signed_callbacks:
Is this property public? It's an addition on this spec.
If public, we need a better description.

2022-11-17 14:56 UTC, pardel commented on definitions/application.v2.yml
> +        conversation_ttl:
Is this property public? It's an addition on this spec.
If public, we need a better description.

2022-11-17 14:56 UTC, pardel commented on definitions/application.v2.yml
> +        payments:
Is this property public? It's an addition on this spec.
If public, we need a better description (including for its properties).

2022-11-21 14:24 UTC, francesco-fipertani-vonage commented on definitions/application.v2.yml
> +        payment_enabled:
Checked with Jamie and he didn't want that flag in the docs

2022-11-21 19:56 UTC, pardel approved these changes

2022-11-21 19:57 UTC, merged